name = "map-the-manor-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

[[routes]]
pattern = "api.mapthemanor.knittedmice.com"
custom_domain = true

[dev]
port = 8787

[[d1_databases]]
binding = "DB"
database_name = "map-the-manor-db"
database_id = "6e25dd35-6bfc-4f99-9151-307a06f5238b"

[triggers]
crons = ["0 3 * * *"]
